name: Update Repo Info

on:
  schedule:
    - cron: "0 0 * * *"  # ✅ Runs daily at midnight to update repo age
  push:                   # ✅ Runs on every push (counts new commits)
  workflow_dispatch:       # ✅ Allows manual trigger

jobs:
  fetch-info:
    runs-on: ubuntu-latest
    permissions: write-all  # ✅ Allows GitHub Actions to push changes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ Uses GitHub's built-in token

      - name: Get Repo Creation Date
        id: repo_info
        run: |
          CREATION_DATE=$(curl -s https://api.github.com/repos/madhurimarawat/Stock-Market-Prediction | jq -r '.created_at' | cut -d'T' -f1)
          echo "CREATION_DATE=$CREATION_DATE" >> $GITHUB_ENV

      - name: Calculate Repository Age
        id: calculate_age
        run: |
          START_DATE=$(date -d "$CREATION_DATE" +%s)
          CURRENT_DATE=$(date +%s)
          AGE_DAYS=$(( (CURRENT_DATE - START_DATE) / 86400 ))
          AGE_YEARS=$(( AGE_DAYS / 365 ))
          AGE_MONTHS=$(( (AGE_DAYS % 365) / 30 ))
          AGE_REMAINING_DAYS=$(( AGE_DAYS % 30 ))
          REPO_AGE="${AGE_YEARS}Y ${AGE_MONTHS}M ${AGE_REMAINING_DAYS}D"
          echo "REPO_AGE=$REPO_AGE" >> $GITHUB_ENV

      - name: Get Total Commits
        id: get_commits
        run: |
          TOTAL_COMMITS=$(curl -s "https://api.github.com/repos/madhurimarawat/Stock-Market-Prediction" | jq -r '.network_count')
          echo "TOTAL_COMMITS=$TOTAL_COMMITS" >> $GITHUB_ENV

      - name: Update README.md with New Badges
        run: |
          # Colors for Badges
          AGE_BADGE_COLOR="%23FFA07A"  # Sunset Orange
          COMMITS_BADGE_COLOR="%23B19CD9"  # Vibrant Lilac

          # Generate Badge URLs
          AGE_BADGE_URL="https://img.shields.io/badge/Repo%20Age-$REPO_AGE-$AGE_BADGE_COLOR?style=for-the-badge&logo=github"
          COMMITS_BADGE_URL="https://img.shields.io/badge/Total%20Commits-$TOTAL_COMMITS-$COMMITS_BADGE_COLOR?style=for-the-badge&logo=git"

          # Replace Badges in README
          sed -i 's|https://img.shields.io/badge/Repo%20Age-[^?]*|'"$AGE_BADGE_URL"'|' README.md
          sed -i 's|https://img.shields.io/badge/Total%20Commits-[^?]*|'"$COMMITS_BADGE_URL"'|' README.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ Uses GitHub's built-in token
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add README.md
          git commit -m "Updated Repository Age & Total Commits Badges" || exit 0
          git push origin main
